# Generated by Django 5.0.6 on 2024-07-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_alter_terceros_apellido1_alter_terceros_apellido2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terceros',
            name='dv',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='terceros',
            name='estadoRut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
